In [1]:
import pandas as pd
from Bio import SeqIO, SearchIO
import json

In [2]:
%cd ../analysis/3.Clustering/3-1.domain_prediction/

/var2/Works/junhyeong/RXLR_landscape/analysis/3.Clustering/3-1.domain_prediction

/home/junhyeong/miniconda3/envs/biopython-env/lib/python3.13/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
df = pd.read_csv("../../1.RXLR_prediction/1-2.pattern_match/Predicted_RXLR_effectors.tsv", sep = "\t")

In [4]:
df

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,RXLR,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,RXLR,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,RXLR,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,RXLR,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,RXLR,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER
...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,RXLR,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,RXLR,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,RXLR,NaN,IEA,RRLR,NaN
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,RXLR,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,RXLR,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN

# Interproscan

In [8]:
# /home/junhyeong/work/project/domain/interproscan/interproscan-5.65-97.0/interproscan.sh

In [5]:
!ls -al

total 12
drwxrwxr-x. 3 junhyeong junhyeong 4096 Dec 16 19:07 .
drwxrwxr-x. 3 junhyeong junhyeong 4096 Dec 16 18:46 ..
drwxrwxr-x. 3 junhyeong junhyeong 4096 Dec 16 18:47 interproscan

In [6]:
with open("interproscan/RXLR_fasta_v3.json") as f:
    data = json.load(f)

In [7]:
pfam_db = {}

for result in data["results"]:

    for match in result["matches"]:

        if not result["xref"][0]["name"] in pfam_db:
            pfam_db[result["xref"][0]["name"]] = []
        
        if match["signature"]["signatureLibraryRelease"]["library"] == "PFAM":
            pfam_db[result["xref"][0]["name"]].append(match["signature"]["description"])
        # elif match["signature"]["signatureLibraryRelease"]["library"] == "PANTHER":
        #     pant_db[result["xref"][0]["name"]] = match["signature"]["name"]

In [10]:
for key, val in pfam_db.items():
    pfam_db[key] = '/'.join(val)

In [13]:
df["PFam"] = df["entry"].map(pfam_db)

In [16]:
df

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif,PFam
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,RXLR,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER,NaN
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,RXLR,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER,"RXLR phytopathogen effector protein, Avirulenc..."
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,RXLR,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER,NaN
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,RXLR,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER,"RXLR phytopathogen effector protein, Avirulenc..."
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,RXLR,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER,NaN
...,...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,RXLR,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN,Carboxylesterase family
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,RXLR,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR,NaN
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,RXLR,NaN,IEA,RRLR,NaN,NaN
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,RXLR,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN,Glycosyl hydrolases family 18
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,RXLR,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN,NaN

In [18]:
df[["entry", "spp", "PFam"]].to_csv("Predicted_Pfam_annotation_in_RXLR_effectors.tsv", sep = "\t", index = False)

# WY PFAM

In [5]:
# !conda run -n homology-env hmmsearch -T 0.0 -o WY_hmmsearch.results ./wy/WY.hmm ../RXLR_db/RXLR_fasta_v3.fasta

In [6]:
!ls -al

total 284
drwxrwxr-x. 5 junhyeong junhyeong   4096 Dec 17 10:36 .
drwxrwxr-x. 6 junhyeong junhyeong   4096 Feb 25 12:34 ..
drwxrwxr-x. 3 junhyeong junhyeong   4096 Dec 16 18:47 interproscan
drwxrwxr-x. 2 junhyeong junhyeong   4096 Dec 17 10:43 .ipynb_checkpoints
-rw-rw-r--. 1 junhyeong junhyeong 118265 Dec 16 19:20 Predicted_Pfam_annotation_in_RXLR_effectors.tsv
-rw-rw-r--. 1 junhyeong junhyeong 149687 Dec 16 19:50 Predicted_WY_annotation_in_RXLR_effectors.tsv
drwxrwxr-x. 3 junhyeong junhyeong   4096 Feb 11 17:21 wy

In [7]:
wy_domain = {}

for query in SearchIO.parse("wy/WY_hmmsearch.results", "hmmer3-text"):
    for hit in query:
        if hit.bitscore > 0:
            wy_domain[hit.id] = len(hit.hsps)

In [8]:
df["WY"] = df["entry"].map(wy_domain)

In [9]:
df["WY"] = df["WY"].fillna(0)

# LWY PFAM

In [10]:
# !conda run -n homology-env hmmsearch -T 0.0 -o ./wy/LWY_hmmsearch.results ./wy/LWY.hmm ../RXLR_db/RXLR_fasta_v3.fasta

In [11]:
lwy_domain = {}

for query in SearchIO.parse("wy/LWY_hmmsearch.results", "hmmer3-text"):
    for hit in query:
        lwy_domain[hit.id] = sum(1 if hsp.bitscore > 30 else 0 for hsp in hit.hsps )

In [12]:
df["LWY"] = df["entry"].map(lwy_domain)

In [13]:
df["LWY"] = df["LWY"].fillna(0)

In [14]:
df

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif,WY,LWY
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,RXLR,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER,0.0,0.0
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,RXLR,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER,0.0,0.0
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,RXLR,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER,5.0,5.0
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,RXLR,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER,2.0,0.0
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,RXLR,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,RXLR,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN,0.0,0.0
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,RXLR,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR,1.0,0.0
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,RXLR,NaN,IEA,RRLR,NaN,0.0,0.0
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,RXLR,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN,0.0,0.0
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,RXLR,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN,0.0,0.0

In [15]:
rxlr_type = []

In [16]:
for idx in df.index:
    
    if df.loc[idx, "LWY"] != 0:
        rxlr_type.append("LWY")
    elif df.loc[idx, "WY"] != 0:
        rxlr_type.append("WY")
    else:
        rxlr_type.append("no (L)WY")

In [17]:
df["type"] = rxlr_type

In [18]:
df

,entry,seq,spp,type,EER,effector_domain,RXLR motif,EER motif,WY,LWY
0,Phyca11_503811,CISLSSAANAPTTSNGVRRLRLAVDVQEERGIADVLSGAITSMKAK...,Phycap,no (L)WY,True,GIADVLSGAITSMKAKVTTNSGKIVEGLKTTAQLSDDQAAKMAKIF...,RRLR,EER,0.0,0.0
1,Phyca11_5186,CNATAVSDQGKTPTVHSLDARLNDDTGDRRSLRAFKEKEEFDTEER...,Phycap,no (L)WY,True,DPSKADDAYKTWADKGYTLSQLSGFLTSKTKGKYDRVYNGYAIHLDY,RSLR,EER,0.0,0.0
2,Phyca11_130393,ETHITSNVQLHSEDIVRRLRFAPEQVEERGLTVPKFQDIVNNQQLA...,Phycap,LWY,True,GLTVPKFQDIVNNQQLAWWLKRGKTTDDVFAKLKLNLAGSSIFENP...,RRLR,EER,5.0,5.0
3,Phyca11_109432,DPASVAAVHSSRVLSDEDKRFLRRHPTEHDNEERAFGQNMFAALKL...,Phycap,WY,True,AFGQNMFAALKLSKMKTDAEYRVKVFHRWKKHGYTADDVAKHVPAK...,RFLR,EER,2.0,0.0
4,Phyca11_129643,VNPTHDERLLRTSTSTKTSTSETEERAIDAAMIARLNDEWQAAVMR...,Phycap,WY,True,AIDAAMIARLNDEWQAAVMRAAYAHWFEGGKTKADVRLIMSLPPTG...,RLLR,EER,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4320,Phyker_46568.2573,ALRSSSSSSMPEIELDYSTIRAVAANETVGYYKYQNIRFAAVPTGD...,Phyker,no (L)WY,NaN,FAAPEFPPQETETNTGTNLADADVDCSSTEDCLYLDVWAPANATNL...,GDLR,NaN,0.0,0.0
4321,Phyker_46568.713,DSPADARALNVVSNERGAKRSLRTMNEESNEVDSTDEADGTEEEDR...,Phyker,WY,True,ILFMGRLKNKWDLRSMRKAADKDFKKQAKELEKLDKAAKKQQKQID...,RSLR,EDR,1.0,0.0
4322,Phyker_46568.8989,GSSTATTAKPEEVYAAVFRVKDGKVTDAMLKDINQNDGSVYYLNQD...,Phyker,no (L)WY,NaN,IEA,RRLR,NaN,0.0,0.0
4323,Phyker_46568.8775,IHLTTVAWNEDKELLCHAHNKGVKVVVKHNFDDVEQLCNATARRDW...,Phyker,no (L)WY,NaN,RELELHPLTRNSQITFDVPWAPRGVDGRYYPWRELAGAVDFLFVMS...,QELR,NaN,0.0,0.0
4324,Phyker_46568.7290,APQPRNLRQNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVS...,Phyker,no (L)WY,NaN,QNSEAAAEFAAKPADDSGRTRLQDSTNPLKRRDQALVSAHRVYDPV...,RNLR,NaN,0.0,0.0

In [21]:
tmp = df[["entry", "spp", "WY", "LWY", "type"]]

In [25]:
tmp[tmp["type"] == "no (L)WY"].groupby("spp").count()

        entry   WY  LWY  type
spp
Brelac    104  104  104   104
Hyaara    105  105  105   105
Phycac    222  222  222   222
Phycap    132  132  132   132
Phycin    227  227  227   227
Phyinf    352  352  352   352
Phyker     87   87   87    87
Phylat     91   91   91    91
Phymeg    603  603  603   603
Phypal    358  358  358   358
Phypar    274  274  274   274
Phyram    123  123  123   123
Physoj    311  311  311   311
Pytaph     81   81   81    81
Pytult     77   77   77    77

In [24]:
tmp[tmp["type"] == "LWY"].groupby("spp").count()

        entry   WY  LWY  type
spp
Brelac      1    1    1     1
Hyaara      3    3    3     3
Phycac     38   38   38    38
Phycap     16   16   16    16
Phycin     32   32   32    32
Phyinf     74   74   74    74
Phyker      1    1    1     1
Phylat     10   10   10    10
Phymeg    112  112  112   112
Phypal     92   92   92    92
Phypar     59   59   59    59
Phyram     32   32   32    32
Physoj     55   55   55    55

In [23]:
tmp[tmp["type"] == "WY"].groupby("spp").count()

        entry   WY  LWY  type
spp
Brelac     12   12   12    12
Hyaara      3    3    3     3
Phycac     56   56   56    56
Phycap     24   24   24    24
Phycin     38   38   38    38
Phyinf     98   98   98    98
Phyker     16   16   16    16
Phylat     16   16   16    16
Phymeg    130  130  130   130
Phypal     98   98   98    98
Phypar     58   58   58    58
Phyram     40   40   40    40
Physoj     64   64   64    64

In [38]:
df[["entry", "spp", "WY", "LWY", "type"]].to_csv("Predicted_WY_annotation_in_RXLR_effectors.tsv", sep = "\t", index = False)

# prism

In [43]:
prism = df.groupby("spp", as_index = False)[["WY-type", "LWY-type", "other domain", "no L, W, Y"]].sum()

In [56]:
prism = prism.div(prism.sum(axis = 1), axis = 0)

In [49]:
prism.set_index("spp", inplace = True)

In [66]:
prism.to_csv("RXLR_WY_prism.txt", sep = "\t")

In [63]:
prism

         WY-type  LWY-type  other domain  no L, W, Y
spp
Brelac  0.110092  0.009174      0.174312    0.706422
Hyaara  0.027778  0.027778      0.175926    0.768519
Phycac  0.190476  0.129252      0.193878    0.486395
Phycap  0.142857  0.095238      0.208333    0.553571
Phycin  0.139194  0.117216      0.201465    0.542125
Phyinf  0.196000  0.148000      0.092000    0.564000
Phyker  0.164948  0.010309      0.309278    0.515464
Phylat  0.142857  0.089286      0.294643    0.473214
Phymeg  0.159314  0.137255      0.074755    0.628676
Phypal  0.183521  0.172285      0.104869    0.539326
Phypar  0.150259  0.152850      0.150259    0.546632
Phyram  0.211640  0.169312      0.222222    0.396825
Physoj  0.162025  0.139241      0.141772    0.556962
Pytaph  0.000000  0.000000      0.662500    0.337500
Pytult  0.000000  0.000000      0.597403    0.402597

In [70]:
wy_n = df[df["WY-type"]].groupby("WY").count()[["entry"]]

In [71]:
lwy_n = df[df["LWY-type"]].groupby("LWY").count()[["entry"]]

In [76]:
count = pd.concat([wy_n, lwy_n], axis = 1)

In [77]:
count.columns = ["wy", "lwy"]

In [80]:
count.fillna(0, inplace = True)

In [82]:
count.to_csv("RXLR_WY_LWY_count_per_number.txt", sep = "\t")

In [85]:
df[df["WY-type"] | df["LWY-type"]]

,entry,seq,plddt,ptm,spp,#Tribe,pfam,WY,LWY,other domain,LWY-type,WY-type,"no L, W, Y"
22,TDH67508.1,MFPSGVGLKRTAGIPFETRPLKMSKSEADAVIKRIYHHANEHIDIA...,53.007620,0.36,Brelac,NaN,NaN,5.0,0.0,False,False,True,False
32,TDH68495.1,FGVVGSNQSESMPDGVDLGEDSYMDTVYFKLWRLHDKLPGEVYNDL...,80.849595,0.66,Brelac,NaN,NaN,1.0,0.0,False,False,True,False
33,TDH68663.1,VSVGSNQSGTMQDEADIGEDSYMDTVYFKLWRLIGKTPGEVYTDSF...,81.540135,0.68,Brelac,NaN,NaN,1.0,0.0,False,False,True,False
34,TDH68883.1,VSVGSNQSGTMQDEADIGEDSYMDTVYFKLWRLIGKTPGEVYTDSF...,81.540135,0.68,Brelac,NaN,NaN,1.0,0.0,False,False,True,False
38,TDH69160.1,AWWENAVQELRWRVKGPGDFFKSLDAVRKGKDLHTDRSFQWWLHRA...,81.971264,0.78,Brelac,NaN,NaN,2.0,0.0,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3965,XP_009539115.1,GITINTKQIDDWLEKGDTADDIFKLLSLHMKESNILANPKLDEWIT...,89.876115,0.81,Physoj,RxLRfam1,NaN,5.0,5.0,False,True,False,False
3971,XP_009539500.1,STEKRRRQTSDIAVLCQKLMNTSKAKKVAKTLQHHLFQAWNNRGMR...,81.838851,0.71,Physoj,NaN,NaN,1.0,1.0,False,True,False,False
3974,XP_009539938.1,AIGDAIGGAITGLASKVQLKFDLRNLLNEGKSADDALALLKFDDKV...,92.612481,0.87,Physoj,RxLRfam1,NaN,3.0,2.0,False,True,False,False
3975,XP_009539958.1,AFSFKSIFGAKKAKIPDDFAVDKLKLMLRSKTLKNNMFQVWDGKYS...,85.043457,0.72,Physoj,NaN,NaN,2.0,0.0,False,False,True,False
3977,XP_009540105.1,VSGENLFGALKVLKMGRDVNYRDKVFQRWKNYGHTKKSVLEKGVPD...,93.073898,0.80,Physoj,NaN,"RXLR phytopathogen effector protein, Avirulenc...",1.0,0.0,False,False,True,False

# ITOL

In [87]:
df

,entry,seq,plddt,ptm,spp,#Tribe,pfam,WY,LWY,other domain,LWY-type,WY-type,"no L, W, Y"
0,TDH64719.1,VAMTTDVVMHGGIVGKLKELLPNNDISNPFSKTRPSKTVTNSYGFN...,33.366736,0.24,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
1,TDH64798.1,ELFLKRSNVPFSIREAYNRNLQEHMTYLEDVNMYARQVRHEFSYDM...,88.604146,0.82,Brelac,NaN,Papain family cysteine protease,0.0,0.0,True,False,False,False
2,TDH65555.1,YGWRYPLRYWNRFGRPLFGSNCRFGRPWVGQLDVARCDDEKKEAEK...,67.174348,0.35,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
3,TDH65737.1,YGWRYPLRYWNRKKERGEKEAFDVMTSSFMHIE,80.266667,0.37,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
4,TDH65748.1,NKGFIYTLNKLHVWNMLEYERVVYLDADNILIRNSDELFLCGEFCA...,76.312921,0.69,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4133,PYU1_T007635,KDGTVDLVIELAQTTESTLESIQETAFSSRTAKVEAIKSKLQAQSK...,95.434218,0.95,Pytult,NaN,Subtilase family,0.0,0.0,True,False,False,False
4134,PYU1_T002439,SDSGSGSVHEDENKTATHIFKSASDVKVGPGIVAAGAIVVGLVVCL...,76.487947,0.66,Pytult,NaN,Domain of unknown function (DUF4203),0.0,0.0,True,False,False,False
4135,PYU1_T003553,QQGFVNLIVILADTTESTLESIQESEYATRTDRINALKSKLEAGNK...,96.082014,0.95,Pytult,NaN,Subtilase family,0.0,0.0,True,False,False,False
4136,PYU1_T003569,VQGNYGGGGGATQSTGGASMSAGASGGAYDSSSGKTSSSGVKSSSS...,41.648927,0.12,Pytult,NaN,NaN,0.0,0.0,False,False,False,True
4137,PYU1_T008793,GDVNCGAPPQVYQGTASYSSTKAGATVRYSCIRGCVMRGSATATCT...,82.587317,0.66,Pytult,NaN,Sushi repeat (SCR repeat),0.0,0.0,True,False,False,False

In [89]:
lwy_type = df[df["LWY-type"]]

In [91]:
lwy_type["color"] = "#0000ff"

/tmp/ipykernel_1048300/534582282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lwy_type["color"] = "#0000ff"

In [102]:
lwy_type["type"] = "LWY"

/tmp/ipykernel_1048300/899100723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lwy_type["type"] = "LWY"

In [95]:
wy_type = df[df["WY-type"]]

In [99]:
wy_type["color"] = wy_type["WY"].map(lambda x: "#ff7f00" if x > 1 else "#ff0000")

/tmp/ipykernel_1048300/3741000003.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wy_type["color"] = wy_type["WY"].map(lambda x: "#ff7f00" if x > 1 else "#ff0000")

In [103]:
wy_type["type"] = wy_type["WY"].map(lambda x: "multi-WY" if x > 1 else "single-WY")

/tmp/ipykernel_1048300/435048157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wy_type["type"] = wy_type["WY"].map(lambda x: "multi-WY" if x > 1 else "single-WY")

In [105]:
colors = pd.concat([lwy_type, wy_type])[["entry", "color", "type"]]

In [108]:
colors.to_csv("../WY_tree/rxlr_type_annotation_colorstrip.txt", sep = "\t", index = False, header = False)

,entry,seq,plddt,ptm,spp,#Tribe,pfam,WY,LWY,other domain,LWY-type,WY-type,"no L, W, Y"
0,TDH64719.1,VAMTTDVVMHGGIVGKLKELLPNNDISNPFSKTRPSKTVTNSYGFN...,33.366736,0.24,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
1,TDH64798.1,ELFLKRSNVPFSIREAYNRNLQEHMTYLEDVNMYARQVRHEFSYDM...,88.604146,0.82,Brelac,NaN,Papain family cysteine protease,0.0,0.0,True,False,False,False
2,TDH65555.1,YGWRYPLRYWNRFGRPLFGSNCRFGRPWVGQLDVARCDDEKKEAEK...,67.174348,0.35,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
3,TDH65737.1,YGWRYPLRYWNRKKERGEKEAFDVMTSSFMHIE,80.266667,0.37,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
4,TDH65748.1,NKGFIYTLNKLHVWNMLEYERVVYLDADNILIRNSDELFLCGEFCA...,76.312921,0.69,Brelac,NaN,NaN,0.0,0.0,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4133,PYU1_T007635,KDGTVDLVIELAQTTESTLESIQETAFSSRTAKVEAIKSKLQAQSK...,95.434218,0.95,Pytult,NaN,Subtilase family,0.0,0.0,True,False,False,False
4134,PYU1_T002439,SDSGSGSVHEDENKTATHIFKSASDVKVGPGIVAAGAIVVGLVVCL...,76.487947,0.66,Pytult,NaN,Domain of unknown function (DUF4203),0.0,0.0,True,False,False,False
4135,PYU1_T003553,QQGFVNLIVILADTTESTLESIQESEYATRTDRINALKSKLEAGNK...,96.082014,0.95,Pytult,NaN,Subtilase family,0.0,0.0,True,False,False,False
4136,PYU1_T003569,VQGNYGGGGGATQSTGGASMSAGASGGAYDSSSGKTSSSGVKSSSS...,41.648927,0.12,Pytult,NaN,NaN,0.0,0.0,False,False,False,True
4137,PYU1_T008793,GDVNCGAPPQVYQGTASYSSTKAGATVRYSCIRGCVMRGSATATCT...,82.587317,0.66,Pytult,NaN,Sushi repeat (SCR repeat),0.0,0.0,True,False,False,False